<script setup lang="ts">
import QRCode from 'qrcode'
const toast=useToast(),{user}=useUser()
const {data,pending,error,refresh}=await useFetch<any>('/api/admin/production-devices')
const {data:options,refresh:refreshOptions}=await useFetch<any>('/api/admin/production-devices/options')
const busy=ref(false),showForm=ref(false),editing=ref<any>(null),qr=ref(''),activation=ref<any>(null),history=ref<any>(null),showHistory=ref(false)
const form=ref({name:'',enterpriseId:String(user.value?.enterprise_id||''),lineName:''})
const lines=computed(()=>[...new Set<string>((options.value?.lines||[]).filter((r:any)=>String(r.enterprise_id)===form.value.enterpriseId).map((r:any)=>r.line_name))])
const labels:Record<string,string>={pending:'待激活',enabled:'启用',disabled:'停用',deleted:'已删除'}
const actions:Record<string,string>={create:'登记',activation:'生成激活码',activated:'设备激活',edit:'编辑',enable:'启用',disable:'停用',delete:'删除'}
let timer:ReturnType<typeof setInterval>|undefined
onMounted(()=>{timer=setInterval(()=>{if(document.visibilityState==='visible'&&!busy.value)void refresh()},15000)})
onBeforeUnmount(()=>clearInterval(timer))
const msg=(e:any)=>e?.data?.statusMessage||'操作尚未确认，请刷新后重试'
function edit(row?:any){editing.value=row||null;form.value={name:row?.name||'',enterpriseId:String(row?.enterprise_id||user.value?.enterprise_id||''),lineName:row?.line_name||''};showForm.value=true;void refreshOptions()}
async function displayActivation(result:any){activation.value=null;qr.value=await QRCode.toDataURL(result.activationCode,{width:320,errorCorrectionLevel:'M',margin:3});activation.value={...result,expiresAt:Date.now()+result.expiresIn*1000}}
async function save(){busy.value=true;try{const body={...form.value,enterpriseId:Number(form.value.enterpriseId)};const result=editing.value?await $fetch<any>('/api/admin/production-devices/'+editing.value.id,{method:'PATCH',body:{...body,action:'edit'}}):await $fetch<any>('/api/admin/production-devices',{method:'POST',body});showForm.value=false;await refresh();await refreshOptions();if(result.activationCode)await displayActivation(result);else toast.add({title:'设备信息已保存',color:'success'})}catch(e){toast.add({title:msg(e),color:'error'})}finally{busy.value=false}}
async function action(row:any,action:string){
  if(['delete','disable','activate'].includes(action)&&!window.confirm(action==='delete'?'删除此设备？历史采集记录保留，设备凭证将撤销。':action==='disable'?'停用此设备？云端停止接受新的生产绑定，本机记录保留。':'重新生成激活码？旧凭证和旧激活码将失效，原设备须重新扫码激活。'))return
  busy.value=true;try{const result=await $fetch<any>('/api/admin/production-devices/'+row.id,{method:'PATCH',body:{action}});await refresh();if(result.activationCode)await displayActivation(result);else toast.add({title:'设备已'+(actions[action]||'更新'),color:'success'})}catch(e){toast.add({title:msg(e),color:'error'})}finally{busy.value=false}
}
async function loadHistory(row:any){try{history.value={name:row.name,...await $fetch<any>('/api/admin/production-devices/'+row.id+'/history')};showHistory.value=true}catch(e){toast.add({title:msg(e),color:'error'})}}
</script>
<template>
  <section class="space-y-4">
    <div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-xl font-semibold">生产设备</h2><p class="text-sm text-muted">登记公司与生产线，扫描仪扫码激活后自动进入生产任务。</p></div><div class="flex gap-2"><UButton variant="outline" :loading="pending" @click="refresh()">刷新</UButton><UButton :disabled="busy" @click="edit()">添加设备</UButton></div></div>
    <p v-if="error" class="text-error">设备列表加载失败，请刷新。</p>
    <div class="overflow-x-auto"><table class="b-table w-full"><thead><tr><th>设备</th><th>公司 / 生产线</th><th>状态</th><th>最近在线 / 同步</th><th>采集情况</th><th>操作</th></tr></thead><tbody><tr v-for="r in data?.rows||[]" :key="r.id"><td>{{ r.name }}<br><small>设备{{ r.id }} · {{ r.model||'尚未激活' }}</small></td><td>{{ r.enterprise_name }}<br>{{ r.line_name }}</td><td>{{ labels[r.status] }}</td><td>{{ r.last_seen_at||'-' }}<br>{{ r.last_sync_at||'-' }}</td><td>{{ r.active_sessions }} 个未结束会话<br>上报待同步：{{ r.reported_pending===null?'未上报':r.reported_pending }}</td><td><div class="flex flex-wrap gap-2"><UButton size="xs" variant="outline" :disabled="busy" @click="edit(r)">编辑</UButton><UButton size="xs" variant="outline" :disabled="busy" @click="action(r,'activate')">{{ r.status==='pending'?'激活二维码':'重新激活' }}</UButton><UButton v-if="r.status==='enabled'||r.status==='pending'" size="xs" variant="outline" :disabled="busy" @click="action(r,'disable')">停用</UButton><UButton v-if="r.status==='disabled'" size="xs" variant="outline" :disabled="busy" @click="action(r,'enable')">启用</UButton><UButton size="xs" variant="outline" @click="loadHistory(r)">记录</UButton><UButton size="xs" color="error" variant="outline" :disabled="busy" @click="action(r,'delete')">删除</UButton></div></td></tr><tr v-if="!pending&&!data?.rows?.length"><td colspan="6" class="py-8 text-center text-muted">暂无设备，点击“添加设备”登记第一台扫描仪。</td></tr></tbody></table></div>
    <p class="text-sm text-muted">待同步数量来自设备最近上报，离线时可能未更新。存在未结束采集时，系统禁止删除、重新激活及调换公司或生产线；停用后可恢复启用继续同步。</p>
    <UModal v-model:open="showForm" :title="editing?'编辑设备':'添加设备'"><template #body><form id="device-form" class="space-y-4" @submit.prevent="save"><fieldset :disabled="busy" class="space-y-4"><label class="block">设备名称<input v-model="form.name" required maxlength="100" placeholder="例如：扫描仪001" class="mt-1 w-full rounded border p-2"></label><label v-if="user?.role==='platform_admin'" class="block">所属公司<select v-model="form.enterpriseId" required class="mt-1 w-full rounded border p-2" @change="form.lineName=''"><option value="">请选择已入驻公司</option><option v-for="e in options?.enterprises||[]" :key="e.id" :value="String(e.id)">{{ e.name }}</option></select></label><label class="block">生产线<input v-model="form.lineName" list="device-lines" required maxlength="100" placeholder="选择已有生产线，或填写新生产线" class="mt-1 w-full rounded border p-2"><datalist id="device-lines"><option v-for="line in lines" :key="line" :value="line" /></datalist></label><p class="text-sm text-muted">添加后用扫描仪扫描激活二维码，无需手动输入设备号。调换公司后需要重新激活。</p></fieldset></form></template><template #footer><UButton type="submit" form="device-form" :loading="busy">{{ editing?'保存':'登记并生成激活二维码' }}</UButton><UButton variant="outline" :disabled="busy" @click="showForm=false">取消</UButton></template></UModal>
    <UModal :open="!!activation" title="扫描仪扫码激活" @update:open="v=>{if(!v)activation=null}"><template #body><div class="text-center space-y-3"><img :src="qr" alt="一次性设备激活二维码" class="mx-auto h-80 w-80"><p>打开 APK 的“扫码激活设备”，用扫描头扫描此二维码。</p><p class="text-sm text-muted">有效期10分钟，只能激活一台设备。过期后重新生成。</p></div></template></UModal>
    <UModal v-model:open="showHistory" :title="(history?.name||'设备')+' · 管理记录'"><template #body><ul class="space-y-4"><li v-for="r in history?.rows||[]" :key="r.id"><b>{{ actions[r.action]||r.action }}</b> · {{ r.actor_name||'设备本人' }}<p class="text-sm text-muted">{{ r.created_at }}</p><p v-if="r.action==='edit'" class="text-sm">{{ r.detail?.before?.name }} / {{ r.detail?.before?.lineName }} → {{ r.detail?.after?.name }} / {{ r.detail?.after?.lineName }}</p></li></ul></template></UModal>
  </section>
</template>
<style scoped>.b-table th,.b-table td{padding:.75rem;text-align:left;border-bottom:1px solid var(--b-divider);vertical-align:top}.b-table small{color:var(--ui-text-muted)}</style>
