plugins { id 'java-library' }
java { sourceCompatibility = JavaVersion.VERSION_17; targetCompatibility = JavaVersion.VERSION_17 }
tasks.withType(Test).configureEach { systemProperty 'test.runtime.classpath', sourceSets.test.runtimeClasspath.asPath }
dependencies {
    compileOnly 'org.json:json:20240303'
    testImplementation 'org.json:json:20240303'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.xerial:sqlite-jdbc:3.46.1.0'
    testRuntimeOnly 'org.slf4j:slf4j-nop:2.0.13'
}
